const ACTION_TYPE = {
    SET_ACCESS_TOKEN: 'SET_ACCESS_TOKEN',
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    UPDATE_USER_AVATAR: 'UPDATE_USER_AVATAR',
    GET_NEW_TOKEN: 'GET_NEW_TOKEN',

}
export default ACTION_TYPE